### ISSUE TITLE
Merging Stencils

### ISSUE THREAD

**Issue by mabicca** [Microsoft/threat-modeling-templates#13]
Hi there,

What would be the easiest way to merge stencils? I have noticed that a lot of useful SDL ones are in the default stencil but not in the Azure one, for example, HTTPS traffic which is very common on threat models.

It would be nice to possibly get the option or at least an stencil pack that has both of best worlds. I don't mind creating a new stencil with that, but first would like to know if there is any easier way to possibly merge them together and then edit so we can still use the same icons and what not.

Thank you,
-Marco

**Comment by parulgarg** [comment]
Once you open a template in the template editor , under File Menu there is an option "Merge Template to This" and you can use that option.

**Comment by nuggetinu** [comment]
I 've received the below feedback from Microsoft, since when you try to merge all 3 templates provided, some errors occur. Basically Microsoft doesn't recommend/support the "merge" function in their tool. Would it be possible to assist in merging all 3 templates using and XML editor and provide 1 combined template? The community will benefit from such template as choosing either of the templates leaves us with missing vital components from the other templates.

Unfortunately, I'm not that versed into XML, even more merging them.

Would really thank you if you can assist on this.



![Threatmodel](https://user-images.githubusercontent.com/31682767/101241958-dba9e300-36fa-11eb-917b-befebce73770.png)
