### ISSUE TITLE
Template Adoption with TM 2016 Tool

### ISSUE THREAD

**Issue by HashmiRSA** [Microsoft/threat-modeling-templates#9]
Like to understand if there are particular steps to adopt this template for the new and old TM files. If I try to open these new tb7 files in TM 2016 as a template or just pick 'Azure Cloud Service.tb7', it throws deserialization error. VSCode hasn't pointed out any XML document errors either.

![image](https://user-images.githubusercontent.com/24576827/35340240-2fbdac52-00e8-11e8-8dfc-0334374c82f4.png)

**Comment by alunmj** [comment]
The TB7 files are templates for the Threat Modeling Tool, which allow you to edit the Stencils, Threats and Threat Properties to be used when creating a new TM7 file, which contains the threat model itself.
Because the TB7 file used to create a TM7 file is used to populate parts of that TM7 file, there's no way to take a new/modified TB7 file and apply it to an existing TM7 file. I'm able to download and then open these template files in the 2016 and Preview versions of the Threat Modelling Tool. I can even create a new Model with the stencils showing for the new Template, indicating that it's been successfully loaded.

**Comment by tombei** [comment]
This is likely because you have saved a HTML file from GIT repo instead of .tb7
